# Generated by Django 4.2.3 on 2023-11-11 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fondo',
            new_name='Fund',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='id_prestamista',
            new_name='id_moneylender',
        ),
    ]
