# Generated by Django 4.2.3 on 2024-01-03 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_rename_amount_loandetail_ammount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loandetail',
            old_name='ammount',
            new_name='amount',
        ),
    ]
